name: PR Build
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build-ppx:
    name: PR Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install OPAM and OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.12.1
      - name: Install OCaml Dependencies and build
        run: |
          cd ppx_src
          opam install dune
          eval $(opam env)
          opam install -y . --deps-only
          dune build
      - name: Install Yarn Dependencies
        run: yarn
      - name: Build Library
        run: yarn build-lib
      - name: Run tests
        run: yarn test
